Signup
santiago-abstracta/digital-bank-bugbusters pull request #1
Opened 2022-01-03 14:51 UTC by santiago-abstracta

Hi! I'm creating this pull request in order to merge the **signup** branch into main. This is a list of all the changes it makes:

- Updates logout.test.js; one of the test-cases had the `only` property, so it was deleted to run all tests. 
- Adds sign up test-cases.
- Updates base and sign up pages:
   - Adds web elements in sign up page.
   - Adds methods to sign up.
   - Adds methods to generate a random _Social Security Number_ and _Email Address_.
- Adds sign up data sets.
- Adds sign up test-cases and updates documentation.
- Updates wdio.conf.js and package-lock.json.

2022-01-03 16:33 UTC, rquintana-abstracta commented on pages/signup.page.js
> +    if (gender == "M") await this.clickElement(this.genderMasculineRadioButton);
As there are only two genders in this radio button set, you can simplify this to a one-liner expression using the **ternary operator** to something like:

```javascript
async clickGenderRadioButton(gender) {
await this.clickElement(gender == 'M' ? this.genderMasculineRadioButton : this.genderFeminineRadioButton) 
}

```

2022-01-03 16:46 UTC, rquintana-abstracta commented on pages/signup.page.js
> +    for (let i = 15; i--; )
Consider using standard for loop signature here, to support the [**principle of least astonishment**](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), as, considering you are not really using the index here, and you're just using a for loop only to make sure you loop a set amount of times to build a username, that means the increment / decrement pattern of your index is not really relevant for your problem here, so you can safely use the standard form of a for loop, that is more straightforward to understand and makes full use of the three optional expressions a for loop typically have (and programmers expect, most of the time)

```javascript
for(let i=0; i<15; i++)
```

2022-01-03 17:00 UTC, rquintana-abstracta commented on pages/signup.page.js
> +        ? "123456789"
As this is test data, it's in the wrong abstraction level. Test data belong to the test, so page objects, same than with notions of success or failure, should not know about them

2022-01-03 17:00 UTC, rquintana-abstracta commented on pages/signup.page.js
> +        ? "jsmith@demo.io"
Same comment about test data

2022-01-03 17:05 UTC, rquintana-abstracta commented on pages/signup.page.js
> +  async signUpWithSuccess(account) {
You are mixing notions of successful or failures here, that conceptually belong to the test. Make sure you make your `SingUpPage` class agnostic of such things. One way of doing it could be splitting form filling in two, as there are two groups of fields separated by clicking the next button, and then handling completion of each sub-set at test level. For some tests, only the first sub-group would be excercised, for example.

2022-01-03 17:06 UTC, rquintana-abstracta commented on pages/signup.page.js
> +  async signUpWithError(account) {
Same issue with success and failure being coupled with page object definition.

2022-01-03 17:08 UTC, rquintana-abstracta requested changes
Implement suggested changes

2022-01-04 15:38 UTC, santiago-abstracta commented on pages/signup.page.js
> +    if (gender == "M") await this.clickElement(this.genderMasculineRadioButton);
Done!

2022-01-04 15:39 UTC, santiago-abstracta commented on pages/signup.page.js
> +    for (let i = 15; i--; )
Done!

2022-01-04 16:14 UTC, santiago-abstracta commented on pages/signup.page.js
> +        ? "123456789"
Done!

2022-01-04 16:15 UTC, santiago-abstracta commented on pages/signup.page.js
> +        ? "jsmith@demo.io"
Done!

2022-01-04 16:15 UTC, santiago-abstracta commented on pages/signup.page.js
> +  async signUpWithSuccess(account) {
Done!

2022-01-04 16:16 UTC, santiago-abstracta commented on pages/signup.page.js
> +  async signUpWithError(account) {
Done!

2022-01-04 22:12 UTC, rquintana-abstracta approved these changes

2022-01-04 22:22 UTC, merged