savings and new savings tests and page objects
santiago-abstracta/digital-bank-bugbusters pull request #2
Opened 2022-01-04 00:34 UTC by carperimb

Savings branch:
- 3 tests implemented for View Savings
- 2 tests implemented for New Savings
- 2 page objects created

2022-01-04 17:34 UTC, rquintana-abstracta commented on pages/newsavings.page.js
> +    async createSavings(name, deposit){
This name implies that you are creating a savings account when calling it, which is not the case (you are configuring the fields, but not yet submitting the data, which is needed to actually create the account). Rename it to something like `completeSavingsAccountForm()` that better expresses what the method actually does.

2022-01-04 17:35 UTC, rquintana-abstracta commented on pages/newsavings.page.js
> +    get selectAccountType(){return $('//*[@id="Savings"]')};
Why there is no specific attribute for each type of account type? Probably in tests you'll need to sometimes select the Money Market option

2022-01-04 17:35 UTC, rquintana-abstracta commented on pages/newsavings.page.js
> +    get selectAccountOwner(){return $ ('//*[@id="Individual"]')};
Same with account owner, why there is only representation for one type of account?

2022-01-04 17:42 UTC, rquintana-abstracta commented on pages/savings.page.js
> +    get individualSelector(){return $('//*[@id="79"]/div/label/span[2]')};
This selector is highly dependent on a specific account instance being present (as it seems the id is a dynamic id generated by the application for each account), as opposed to a web element specific id. See if you can decouple your selector from the specific account id, as that way you'll make it more robust and abstracted out from changes in data.

2022-01-04 17:43 UTC, rquintana-abstracta commented on pages/savings.page.js
> +    get jointSelector(){return $('//*[@id="124"]/div/label/span[1]')};
Some comment than before, this is too coupled to the application data. Choose a selector that does not make specific reference to a specific data entity, that your test have no essential control over.

2022-01-04 17:48 UTC, rquintana-abstracta commented on pages/savings.page.js
> +
Also, "selector" has a specific technical meaning in the context of test automation, prefer another name to refer this concept. Something like **jointAccountOwnershipType** which uses domain specific terminology, thus, abstracts the location method away from it

2022-01-04 18:01 UTC, rquintana-abstracta commented on tests/newsavings.test.js
> +        expect(await browser).toHaveUrlContaining('account/savings-view?selectSwitch=173');
Prefer checking for the state / existence of a web element as a means to assert the behaviour you are expecting, as it's more user centric (which is the main characteristic of an e2e test) and matches what a user will typically expect / see for getting feedback of a successful transaction, as opposed to checking a URL. Furthermore, if URL is correct, but no feedback is displayed for the user, that's probably a bug.

Another argument against using URLs when there's a web element for e2e tests, perhaps a bit weaker than the previous ones, is that API tests can easily evaluate URLs, so URL based validations are better implemented at that layer.

2022-01-04 18:07 UTC, rquintana-abstracta commented on tests/newsavings.test.js
> +        expectChai (await newsavingsPage.getDeposit()).to.equal('');
There is a wdio matcher supporting this operation: **toHaveValue()**, that you can call directly on the element represeting the deposit input, as with the rest of wdio matchers. Prefer wdio specific matchers whenever possible, and you'll avoid having to implement methods / functionality for extracting specific attributes from elements.

```javascript
expect(await newsavingsPage.initialDeposit).toHaveValue('')
```

Reference: https://webdriver.io/docs/api/expect-webdriverio/#tohavevalue

2022-01-04 18:21 UTC, rquintana-abstracta commented on tests/savings.test.js
> +        expectChai (await savingsPage.getSavingsTitle()).to.equal('View Savings Accounts');
Same comment as with the other expectChai construct. Prefer wdio specific matcher (I think the **toHaveText()** method would work there)

2022-01-04 18:46 UTC, rquintana-abstracta commented on tests/savings.test.js
> +        expect(await browser).toHaveUrlContaining('account/savings-view?selectSwitch=79');
Same comment about prefering web element based assertions instead of URLs whenever possible

2022-01-04 18:47 UTC, rquintana-abstracta commented on tests/savings.test.js
> +        expect(await browser).toHaveUrlContaining('account/savings-view?selectSwitch=124');
Same comment about prefering web element based assertions instead of URLs whenever possible

2022-01-04 18:51 UTC, rquintana-abstracta commented on tests/newsavings.test.js
> +import savingsPage from '../pages/savings.page';
Standard in wdio is importing page objects using its class name (First letter capitalized)

2022-01-04 18:52 UTC, rquintana-abstracta commented on tests/newsavings.test.js
> +import newsavingsPage from  '../pages/newsavings.page';
Same comment about capitalizing first letter and using general PascalCase convention (in this case would be NewSavingsPage)

2022-01-04 18:52 UTC, rquintana-abstracta commented on tests/savings.test.js
> +import savingsPage from '../pages/savings.page';
Same comment about capitalizing first letter

2022-01-04 18:54 UTC, rquintana-abstracta commented on tests/newsavings.test.js
> +describe ('NewSavings', () => {
Consider implementing more tests, as there are lots of account type combinations that wheren't covered here (combinations of individual, joint, savings and new money configurations, for example)

2022-01-04 18:56 UTC, rquintana-abstracta commented on tests/savings.test.js
> +describe ('Savings', () => {
Consider implementing more tests here as well, as there is functionality that has not been excercised here, such as table related flows (searching, validating sums of individual records vs total, asserting that the total that appears on Account summary is the same that the one that appears on the table, page filtering, etc)

2022-01-04 18:56 UTC, rquintana-abstracta requested changes
Implement requested changes and more tests

2022-01-04 22:03 UTC, rquintana-abstracta commented on tests/savings.test.js
> +    });
Make sure to document new test cases as well

2022-01-05 18:40 UTC, carperimb commented on pages/newsavings.page.js
> +    async createSavings(name, deposit){
done

2022-01-05 18:45 UTC, carperimb commented on pages/newsavings.page.js
> +    get selectAccountType(){return $('//*[@id="Savings"]')};
Is it necessary to get every element of the page?

2022-01-05 18:48 UTC, carperimb commented on pages/newsavings.page.js
> +    get selectAccountType(){return $('//*[@id="Savings"]')};
done...

2022-01-05 18:49 UTC, carperimb commented on pages/newsavings.page.js
> +    get selectAccountOwner(){return $ ('//*[@id="Individual"]')};
done

2022-01-05 18:51 UTC, rquintana-abstracta commented on pages/newsavings.page.js
> +    get selectAccountType(){return $('//*[@id="Savings"]')};
I'm assuming you'll write tests for each combination of account types, as that'll cover for more scenarios, that's why I was expecting to see selectors for each account creation parameter specific elements. There is no need for implementing selectors for every element, but IMO, it is important for those that participate in state changing behaviour of a page / functionality, as is the case for account type specific elements.

2022-01-05 19:05 UTC, carperimb commented on pages/savings.page.js
> +
done

2022-01-05 19:21 UTC, carperimb commented on pages/newsavings.page.js
> +    get selectAccountType(){return $('//*[@id="Savings"]')};
ok

2022-01-05 19:33 UTC, carperimb commented on pages/savings.page.js
> +
done

2022-01-05 19:41 UTC, carperimb commented on tests/savings.test.js
> +        expect(await browser).toHaveUrlContaining('account/savings-view?selectSwitch=79');
I cannot find another element to expect cause there's no difference between Individual or Joint page but the url... the transaction table can also change after all.

2022-01-05 19:42 UTC, carperimb commented on tests/savings.test.js
> +        expect(await browser).toHaveUrlContaining('account/savings-view?selectSwitch=124');
Same comment as above...

2022-01-05 19:42 UTC, carperimb commented on tests/newsavings.test.js
> +import savingsPage from '../pages/savings.page';
done

2022-01-05 19:42 UTC, carperimb commented on tests/newsavings.test.js
> +import newsavingsPage from  '../pages/newsavings.page';
done

2022-01-05 19:42 UTC, carperimb commented on tests/savings.test.js
> +import savingsPage from '../pages/savings.page';
done

2022-01-05 19:54 UTC, carperimb commented on tests/savings.test.js
> +        expectChai (await savingsPage.getSavingsTitle()).to.equal('View Savings Accounts');
done

2022-01-05 19:54 UTC, carperimb commented on tests/newsavings.test.js
> +        expectChai (await newsavingsPage.getDeposit()).to.equal('');
done

2022-01-05 19:54 UTC, carperimb commented on tests/newsavings.test.js
> +        expect(await browser).toHaveUrlContaining('account/savings-view?selectSwitch=173');
done

2022-01-05 19:55 UTC, carperimb commented on pages/savings.page.js
> +    get jointSelector(){return $('//*[@id="124"]/div/label/span[1]')};
done

2022-01-05 19:55 UTC, carperimb commented on pages/savings.page.js
> +    get individualSelector(){return $('//*[@id="79"]/div/label/span[2]')};
done

2022-01-05 22:15 UTC, carperimb commented on tests/newsavings.test.js
> +describe ('NewSavings', () => {
done

2022-01-06 14:14 UTC, carperimb commented on tests/newsavings.test.js
> +describe ('NewSavings', () => {
I have a question about deposit amounts lower than minimum cause instead of showing an error message there's a 'popover' and I have no idea how to select this element to prove the test... (after doing FOOYO)

2022-01-06 14:21 UTC, rquintana-abstracta commented on tests/newsavings.test.js
> +describe ('NewSavings', () => {
If that popover is a JS alert, maybe this is what you're looking for: http://v4.webdriver.io/api/protocol/alertText.html

2022-01-06 14:22 UTC, rquintana-abstracta commented on tests/newsavings.test.js
> +describe ('NewSavings', () => {
BTW, good opportunity to suggest more consistency in error messages (So far I've seen badges, html form based feedback and now alerts to signal errors)

2022-01-06 14:35 UTC, carperimb commented on tests/savings.test.js
> +describe ('Savings', () => {
done

2022-01-06 15:13 UTC, carperimb commented on tests/newsavings.test.js
> +describe ('NewSavings', () => {
ok

2022-01-07 13:18 UTC, carperimb commented on tests/savings.test.js
> +    });
done

2022-01-10 14:54 UTC, rquintana-abstracta commented on pages/savings.page.js
> +    get individualSelector(){return $('//*[@id="79"]/div/label/span[2]')};
This is still bounded to a specific application entity id. Consider implementing the element's array based solution, that located every account and then iterate over it to find each specific account you want to interact with, as that solution is agnostic of application data.

2022-01-10 14:55 UTC, rquintana-abstracta commented on pages/savings.page.js
> +    get jointSelector(){return $('//*[@id="124"]/div/label/span[1]')};
Same comment as above

2022-01-10 16:56 UTC, rquintana-abstracta commented on pages/newsavings.page.js
> +    get selectAccountOwnerJoint(){return $ ('#Joint')};
Prefer naming those to something like `options` instead of `select`, as current implementation makes it look like a method definition (like the action of selecting those items), instead of a web element.

eg. `accountTypeSavingsOption` or the like

2022-01-10 17:07 UTC, rquintana-abstracta commented on pages/newsavings.page.js
> +    }
This method is part of a set of 4 methods that share the same overall structure. Consider parameterizing the option selection part as well (that is the only aspect that changes for all them), so you declare only one method that can handle every option combination. Something like:

```javascript
    async completeNewSavingForm(accountType, ownershipType, accountName, depositAmount){
        await super.clickElement(accountType == "savings" ? await this.selectAccountTypeSavings : await this.selectAccountTypeMoneyMarket );
        await super.clickElement(ownershipType =="individual" ? await this.selectAccountOwnerIndividual : await this.selectAccountOwnerJoint );
        await super.completeFieldWithText(await this.accountName, accountName);
        await super.completeFieldWithText(await this.initialDeposit, depositAmount);
    }

```
So you only declare this structure once (instead of 4 times), and then the test drives the data for each configuration.

The construct used for conditionally choosing among different selectors is called the **ternary operator** and it's useful for simple conditional comparisons like this one.

**Reference:** https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

2022-01-10 17:15 UTC, rquintana-abstracta commented on tests/newsavings.test.js
> +const expectChai = require('chai').expect;
Delete this, as you are not using it throughout the tests

2022-01-10 17:18 UTC, rquintana-abstracta commented on tests/newsavings.test.js
> +        expect (NewSavingsPage.getConfirmationMsg).toHaveText('Successfully created new Savings account named testInd');
The expected use for wdio matchers implies a full web element is passed as parameter to the `expect()` function, and then the matcher looks for the specific method that returns the property it needs, therefore only pass it the `confirmationMsg` element, that also implies that the specific method you created for getting the text might be not needed at all (making your overall code base smaller)

2022-01-10 17:19 UTC, rquintana-abstracta commented on tests/newsavings.test.js
> +        expect (NewSavingsPage.getConfirmationMsg).toHaveText('Successfully created new Savings account named testJoint');
Same comment as above

2022-01-10 17:19 UTC, rquintana-abstracta commented on tests/newsavings.test.js
> +        expect (NewSavingsPage.getConfirmationMsg).toHaveText('Successfully created new Savings account named testMMind');
Same comment as above

2022-01-10 17:19 UTC, rquintana-abstracta commented on tests/newsavings.test.js
> +        expect (NewSavingsPage.getConfirmationMsg).toHaveText('Successfully created new Savings account named testMMjoint');
Same comment as above

2022-01-10 17:23 UTC, rquintana-abstracta commented on tests/newsavings.test.js
> +    it ('Should create a new individual savings account when clicking on the submit button and show confirmation message', async () => {
After appying the advice of turning all 4 "form completing methods" into one more general method, the structure for the first 4 tests you created becomes exactly equal. This implies you can benefit from a **data driven approach**, where you declare the structure once, and delegate to a data file the configuration each test need (See the example used in tests for user registration as a guide)

2022-01-10 17:27 UTC, rquintana-abstracta commented on tests/newsavings.test.js
> +describe ('NewSavings', () => {
As this suite creates new entities, and tests need to, as a general rule, "leave the environment in the same state they found it", consider using an **after()** hook to place environment cleaning logic (something that deletes the entities it creates)

2022-01-10 17:27 UTC, rquintana-abstracta commented on tests/savings.test.js
> +        expect (SavingsPage.getSavingsTitle).toHaveText('View Savings Accounts');
Same comment about using the web element directly here instead of a method that accesses element's properties

2022-01-10 20:12 UTC, rquintana-abstracta commented on tests/savings.test.js
> +        expect(await browser).toHaveUrlContaining('account/savings-view?selectSwitch=298'); //cambia dinamicamente!
As your comment states, this URL is dynamically generated (the `selectSwitch` part actually). Consider accounting for that in your design. For example, as that number appears to be related to the ID of the account the card is representing, consider implementing a method that extracts the id of the individual account is detects, and use it to dynamically build the URL you are using for the assertion.

2022-01-10 20:12 UTC, rquintana-abstracta commented on tests/savings.test.js
> +        expect(await browser).toHaveUrlContaining('account/savings-view?selectSwitch=334'); //cambia dinamicamente!
Same comment as above

2022-01-10 20:17 UTC, rquintana-abstracta commented on tests/savings.test.js
> +        expect(SavingsPage.transactionTable).toHaveText('Deposit');
I think this test does not really validate that the search functionality works well. IMO, search works adequately if it only brings back results that contain the searched keywords. This test only validates that there is at least one "Deposit" in the results, but it still passes if there is another kind of entry as well.

Consider looking at every row and validating that all of them include ''Deposit" in it to improve this test.

2022-01-10 20:20 UTC, rquintana-abstracta commented on tests/savings.test.js
> +        expect (SavingsPage.getBalanceCard()).toHaveText(SavingsPage.getBalanceTable());
As you are comparing numeric information, consider parsing the results of those values to a number (implemented as part of those methods), and then compare them (potentially using another matcher than `toHaveText()`, probably some Jest based matcher, like `toBe()` or `toEqual()`)

BTW, remember jest matchers are included in wdio expect(), so no additional configuration is needed to access those.

2022-01-10 20:23 UTC, rquintana-abstracta commented on pages/newsavings.page.js
> +    }
There is a high chance that none of these methods are needed provided that you use the right matcher when asserting the underlying elements they are using. Check that out after you change those assertions

2022-01-10 20:26 UTC, rquintana-abstracta commented on pages/savings.page.js
> +    get balanceCard(){return $ ('//*[@id="298"]/div/div[7]')};
I think this selector refers to the balance that the card representing the account displays there. There are potentially a lot of accounts, so it would be good if you individualize it in this name as well. Maybe something like `IndividualAccountBalance`

2022-01-10 20:30 UTC, rquintana-abstracta commented on pages/savings.page.js
> +    get balanceTable(){return $('//*[@id="transactionTable"]/tbody/tr[1]/td[5]')};
Consider being a little bit more specific here, and also switch the order of each word, as they comply more with english standard of stating the object that belongs to some "parent" object after the parent object, so it ends up something like:
`transactionTableBalance`, as this small change improves readability a lot (also avoiding a potential confusion with the "verb-like" interpretation of "balance") (the act of balancing something, instead of the object "balance")

2022-01-10 20:34 UTC, rquintana-abstracta commented on pages/savings.page.js
> +        await this.individualSwitchHandle.isExisting();
This is not really needed, as BasePage's clickElement already uses a `waitForClickable()` that makes sure the element exists and is clickable before clicking it. I think you did this based on another comment that said something about being explicit about the existence of a given element when it was referred by an id that is bounded to an application entity id.

For now, ignore that, as we're going to try to avoid using that id completely for this case.

2022-01-10 20:34 UTC, rquintana-abstracta commented on pages/savings.page.js
> +        await this.jointSwitchHandle.isExisting();
Same comment as above

2022-01-25 16:22 UTC, carperimb commented on pages/savings.page.js
> +    get individualSelector(){return $('//*[@id="79"]/div/label/span[2]')};
I decided not to use the 'switch-handle'

2022-01-25 16:22 UTC, carperimb commented on pages/savings.page.js
> +    get jointSelector(){return $('//*[@id="124"]/div/label/span[1]')};
I decided not to use the 'switch-handle'

2022-01-25 16:23 UTC, carperimb commented on tests/newsavings.test.js
> +const expectChai = require('chai').expect;
done

2022-01-25 16:48 UTC, carperimb commented on tests/savings.test.js
> +        expect(await browser).toHaveUrlContaining('account/savings-view?selectSwitch=334'); //cambia dinamicamente!
I've decided not to use the 'switch-handle'

2022-01-25 16:51 UTC, carperimb commented on tests/savings.test.js
> +        expect(SavingsPage.transactionTable).toHaveText('Deposit');
![image](https://user-images.githubusercontent.com/96138690/151021700-a0273292-e4aa-44f1-b7a7-7649aea7c5b9.png)
I don't think so... "This test only validates that there is at least one "Deposit" in the results, but it still passes if there is another kind of entry as well."

2022-01-25 17:13 UTC, carperimb commented on pages/newsavings.page.js
> +    get selectAccountOwnerJoint(){return $ ('#Joint')};
done

2022-01-25 17:16 UTC, carperimb commented on pages/newsavings.page.js
> +    }
done

2022-01-25 17:18 UTC, carperimb commented on tests/newsavings.test.js
> +        expect (NewSavingsPage.getConfirmationMsg).toHaveText('Successfully created new Savings account named testInd');
done

2022-01-25 17:19 UTC, carperimb commented on tests/newsavings.test.js
> +        expect (NewSavingsPage.getConfirmationMsg).toHaveText('Successfully created new Savings account named testJoint');
done

2022-01-25 17:20 UTC, carperimb commented on tests/newsavings.test.js
> +        expect (NewSavingsPage.getConfirmationMsg).toHaveText('Successfully created new Savings account named testMMind');
done

2022-01-25 17:20 UTC, carperimb commented on tests/newsavings.test.js
> +        expect (NewSavingsPage.getConfirmationMsg).toHaveText('Successfully created new Savings account named testMMjoint');
done

2022-01-25 17:30 UTC, carperimb commented on tests/savings.test.js
> +        expect (SavingsPage.getSavingsTitle).toHaveText('View Savings Accounts');
done

2022-01-25 17:31 UTC, carperimb commented on tests/savings.test.js
> +        expect (SavingsPage.getBalanceCard()).toHaveText(SavingsPage.getBalanceTable());
I've decided not to test the balance...

2022-01-25 17:32 UTC, carperimb commented on pages/newsavings.page.js
> +    }
done

2022-01-25 17:34 UTC, carperimb commented on pages/savings.page.js
> +    get balanceCard(){return $ ('//*[@id="298"]/div/div[7]')};
I've decided not to test the balance...

2022-01-25 17:34 UTC, carperimb commented on pages/savings.page.js
> +    get balanceTable(){return $('//*[@id="transactionTable"]/tbody/tr[1]/td[5]')};
I've decided not to test the balance...

2022-01-25 17:35 UTC, carperimb commented on pages/savings.page.js
> +        await this.individualSwitchHandle.isExisting();
ok

2022-01-25 17:35 UTC, carperimb commented on pages/savings.page.js
> +        await this.jointSwitchHandle.isExisting();
ok

2022-01-27 19:48 UTC, carperimb commented on pages/savings.page.js
> +    get individualSelector(){return $('//*[@id="79"]/div/label/span[2]')};
Solved

2022-01-27 19:48 UTC, carperimb commented on pages/savings.page.js
> +    get jointSelector(){return $('//*[@id="124"]/div/label/span[1]')};
Solved

2022-01-27 19:50 UTC, carperimb commented on tests/savings.test.js
> +        expect(await browser).toHaveUrlContaining('account/savings-view?selectSwitch=298'); //cambia dinamicamente!
Solved

2022-01-27 19:50 UTC, carperimb commented on tests/savings.test.js
> +        expect(await browser).toHaveUrlContaining('account/savings-view?selectSwitch=334'); //cambia dinamicamente!
Solved

2022-01-27 19:57 UTC, carperimb commented on pages/savings.page.js
> +    get balanceCard(){return $ ('//*[@id="298"]/div/div[7]')};
Solved

2022-01-27 23:17 UTC, carperimb commented on tests/newsavings.test.js
> +    it ('Should create a new individual savings account when clicking on the submit button and show confirmation message', async () => {
done

2022-01-27 23:18 UTC, carperimb commented on tests/newsavings.test.js
> +describe ('NewSavings', () => {
the only way I could find is to delete all the data from the app...

2022-01-28 14:43 UTC, carperimb commented on pages/savings.page.js
> +    get balanceTable(){return $('//*[@id="transactionTable"]/tbody/tr[1]/td[5]')};
done

2022-01-28 14:45 UTC, carperimb commented on tests/savings.test.js
> +        expect(SavingsPage.transactionTable).toHaveText('Deposit');
Implementation changed, the search result must be shown in the 3rd column only...

2022-01-28 15:37 UTC, carperimb commented on tests/savings.test.js
> +        expect (SavingsPage.getBalanceCard()).toHaveText(SavingsPage.getBalanceTable());
Both cases are strings...
I can see the text but I still get an error:
![image](https://user-images.githubusercontent.com/96138690/151575827-8e8a23b0-265f-4619-871d-37f883f9ff14.png)

2022-01-28 15:44 UTC, rquintana-abstracta commented on tests/savings.test.js
> +        expect (SavingsPage.getBalanceCard()).toHaveText(SavingsPage.getBalanceTable());
Put an `await` in front of the expect, as it's working with network resources (therefore you need to explicitly await for the completion of the task to assert it)

2022-01-28 15:55 UTC, carperimb commented on tests/newsavings.test.js
> +describe ('NewSavings', () => {
done

2022-01-31 16:19 UTC, rquintana-abstracta commented on tests/savings.test.js
> +        await expect (SavingsPage.individualBalanceCard.getText()).toHaveText('Balance: '+ SavingsPage.transactionTableBalance.getText());
Couple of comments:

- You don't need `.getText()` when passing the argument to `expect()` here, as it's a wdio specific matcher, only pass it the element and it'll figure out the method to call.

- Prefer **template literals** for string interpolation, instead of concatenation for better readability and shorter expression.

Eg.

```javascript
await expect (SavingsPage.individualBalanceCard).toHaveText(`Balance: ${SavingsPage.transactionTableBalance.getText()}`);
```

2022-01-31 16:20 UTC, rquintana-abstracta commented on tests/savings.test.js
> +        //expect error= Received:undefined
Remove this comment, as I assume it's something for debugging

2022-01-31 16:24 UTC, rquintana-abstracta commented on tests/newsavings.test.js
> +        await HomePage.clickDeleteData();
Encapsulate this a bit more, as the clicking of a user avatar seems like an implementation detail, something this hook doesn't need to know for what you want to express here. Consider creating a method on `HomePage` for deleting data, and another one for creating it that includes clicking on user avatar and clicking the corresponding elements. Something like:

```javascript
async deleteData(){
       await HomePage.clickUserAvatar();
       await HomePage.clickDeleteData();
}

async createData(){
       await HomePage.clickUserAvatar();
       await HomePage.clickCreateData();
}

```

2022-01-31 16:26 UTC, rquintana-abstracta requested changes
Implement requested changes

2022-01-31 17:12 UTC, carperimb commented on tests/savings.test.js
> +        //expect error= Received:undefined
Nop, that's the current error I'm getting back...

2022-01-31 22:05 UTC, carperimb commented on tests/savings.test.js
> +        await expect (SavingsPage.individualBalanceCard.getText()).toHaveText('Balance: '+ SavingsPage.transactionTableBalance.getText());
ok

2022-01-31 22:05 UTC, carperimb commented on tests/newsavings.test.js
> +        await HomePage.clickDeleteData();
ok

2022-01-31 22:12 UTC, carperimb commented on tests/savings.test.js
> +        //expect error= Received:undefined
Now I'm getting back this error:
![image](https://user-images.githubusercontent.com/96138690/151881753-66f7e445-4e6c-4200-9fa0-d07d33a743b4.png)

2022-01-31 22:17 UTC, rquintana-abstracta commented on tests/savings.test.js
> +        //expect error= Received:undefined
This is because the `getText()` operation is asynchronous (returns a promise). Save the value first in a variable (calling the method using await) and then use it inside the expect, like:

```javascript
let tableBalance = await SavingsPage.transactionTableBalance.getText();
await expect (SavingsPage.individualBalanceCard).toHaveText(`Balance: ${tableBalance}`);

```

2022-01-31 22:24 UTC, carperimb commented on tests/savings.test.js
> +        //expect error= Received:undefined
You're like a genie in a bottle man! hahaha
![image](https://user-images.githubusercontent.com/96138690/151883122-2d0e4cc5-5669-4523-8334-1db0d61a2a37.png)

2022-02-01 13:27 UTC, rquintana-abstracta approved these changes

2022-02-01 15:03 UTC, merged