Deposit tests and page objects
santiago-abstracta/digital-bank-bugbusters pull request #3
Opened 2022-01-05 18:34 UTC by carperimb

- 3 tests implemented
- 1 page object

2022-01-10 21:09 UTC, rquintana-abstracta commented on pages/deposit.page.js
> +    get submitButton(){return $('//*[@id="right-panel"]/div[2]/div/div/div/div/form/div[2]/button[1]')};
As a general rule, prefer shorter, unique, and **as independent from context as possible** selectors so they are more robust (less likely to break after changes). This one is too bound to the specific dom structure it belongs to at the moment (that chain of divs basically). You can use a simpler, more targeted css selector expression to locate this element. Something like `button[type="submit"]`

2022-01-10 21:09 UTC, rquintana-abstracta commented on pages/deposit.page.js
> +    get resetButton(){return $('//*[@id="right-panel"]/div[2]/div/div/div/div/form/div[2]/button[2]')};
Same comment as above, this can be located with a simple css selector similar to the one for the submit button. Prefer that option.

2022-01-10 21:13 UTC, rquintana-abstracta commented on pages/deposit.page.js
> +    get transaction(){return $('//*[@id="transactionTable"]/tbody/tr[1]/td[4]')};
This element belongs to some other page (the one the account involved belongs to), so it's out of the scope of this page object. Maybe create some mechanism to interact with the page the transaction belongs to (Maybe exposing a boolean method in that other page that expects a transaction as parameter and returns true if it finds it in its table)

2022-01-10 21:13 UTC, rquintana-abstracta commented on pages/deposit.page.js
> +        //await super.clickElement(await this.jointChecking);
Remove commented code

2022-01-10 21:16 UTC, rquintana-abstracta commented on pages/deposit.page.js
> +    async accountSelector(){
This name is not really descriptive. Make more explicit what action you expect to execute here. Also, if you are always going to select the first account, move that information to the method name as well, to increase readability and expressiveness. Something like: `selectFirstAccountInDropdown()`

2022-01-10 21:21 UTC, rquintana-abstracta commented on pages/deposit.page.js
> +        return await this.transaction.getText();
Based on this element's selector used, this seems to be the information of the last registered transaction (assuming that table is sorted by descending order). Maybe include that information in the name as well: `getLastTransaction()`. Apart from that, this seems to be information conceptually belonging to the transaction table (in its corresponding page object), not this one.

2022-01-10 21:22 UTC, rquintana-abstracta commented on tests/deposit.test.js
> +//import { expect } from "chai";
Remove commented code

2022-01-10 21:26 UTC, rquintana-abstracta commented on tests/deposit.test.js
> +        await DepositPage.setDepositAmount(amount);
This seems to be logic that is repeated throughout all tests. Consider abstracting this out into a higher order method, parameterizing the deposit amount (which seems to be the natural parameter for the method, as it's test data). Could be something like `completeDepositForm(depositAmount)`

2022-01-10 21:27 UTC, rquintana-abstracta commented on tests/deposit.test.js
> +        expectChai (await DepositPage.getDepositAmount()).to.equal('');
No need to use chai here, can use wdio standard matcher: `toHaveValue('')` (same as with Savings account PR)

2022-01-10 21:29 UTC, rquintana-abstracta commented on tests/deposit.test.js
> +        expectChai (await DepositPage.getTransaction()).to.equal('$50.00');
No need for chai here as well, you can use a jest based matcher (already embedded in wdio `expect()` so no extra configuration needed): `toEqual('$50.00')`

2022-01-10 21:29 UTC, rquintana-abstracta commented on tests/deposit.test.js
> +        expect (await depositPage.getPageTitle()).toHaveText('Deposit');
no need for explicitly getting page title, just pass the element to expect() and the matcher figures it out.

2022-01-10 21:30 UTC, rquintana-abstracta commented on tests/deposit.test.js
> +const expectChai = require('chai').expect;
Based on all the comments, chai seems to be unnecessary

2022-01-14 11:15 UTC, carperimb commented on pages/deposit.page.js
> +    get submitButton(){return $('//*[@id="right-panel"]/div[2]/div/div/div/div/form/div[2]/button[1]')};
done

2022-01-14 11:15 UTC, carperimb commented on pages/deposit.page.js
> +    get resetButton(){return $('//*[@id="right-panel"]/div[2]/div/div/div/div/form/div[2]/button[2]')};
done

2022-01-14 11:15 UTC, carperimb commented on pages/deposit.page.js
> +    get transaction(){return $('//*[@id="transactionTable"]/tbody/tr[1]/td[4]')};
done

2022-01-14 11:15 UTC, carperimb commented on pages/deposit.page.js
> +    async accountSelector(){
done

2022-01-14 11:16 UTC, carperimb commented on pages/deposit.page.js
> +        return await this.transaction.getText();
done

2022-01-14 11:16 UTC, carperimb commented on tests/deposit.test.js
> +//import { expect } from "chai";
done

2022-01-14 11:16 UTC, carperimb commented on tests/deposit.test.js
> +        await DepositPage.setDepositAmount(amount);
done

2022-01-14 11:16 UTC, carperimb commented on tests/deposit.test.js
> +        expectChai (await DepositPage.getDepositAmount()).to.equal('');
done

2022-01-14 11:16 UTC, carperimb commented on tests/deposit.test.js
> +        expectChai (await DepositPage.getTransaction()).to.equal('$50.00');
done

2022-01-14 11:18 UTC, carperimb commented on tests/deposit.test.js
> +        expect (await depositPage.getPageTitle()).toHaveText('Deposit');
It gave me the message 'pageTitle' is not a function...

2022-01-14 11:18 UTC, carperimb commented on tests/deposit.test.js
> +const expectChai = require('chai').expect;
done

2022-01-14 17:23 UTC, rquintana-abstracta commented on pages/deposit.page.js
> +    async accountSelector(){
I still see the same name for this function, only change I noticed is index is now parameterized.

2022-01-14 20:21 UTC, rquintana-abstracta commented on pages/deposit.page.js
> +    async completeDepositForm(deposit){
Prefer using a method signature more detached from the shape of test data. For example: ` completeDepositForm(accountIndex, depositAmount)`, as it decouples it from the shape of the data providing for those parameters (In your case, your test data)

2022-01-14 20:26 UTC, rquintana-abstracta commented on tests/deposit.test.js
> +        expectChai (await DepositPage.getDepositAmount()).to.equal('');
I see that you used a wdio matcher now, but you didn't use the most directly applicable one is the `toHaveValue('')` one, as it directly looks for that attribute in the provided element, making it unnecessary to even declare the `getDepositAmount()` method

2022-01-14 21:54 UTC, rquintana-abstracta commented on tests/deposit.test.js
> +            expect(obtainedAccount.getLastTransaction()).toHaveText('$50.00');
you can directly use the web element representing the transaction here with this matcher, no need to declare a `getLastTransaction()` to ge the text first.

2022-01-14 21:57 UTC, rquintana-abstracta commented on tests/deposit.test.js
> +        expect (await depositPage.getPageTitle()).toHaveText('Deposit');
How were you using it? A getter function in js is "called" like you would call an attribute, directly by its name, like `DepositPage.pageTitle` without the parenthesis.

2022-01-14 22:09 UTC, rquintana-abstracta commented on tests/deposit.test.js
> +            expect (await DepositPage.getDepositAmount()).toHaveText('');
Same comment here about preferring using `toHaveValue('')` directly over the method representing the deposit amount input (and therefore not needing the explicit `getDepositAmount()` method)

2022-01-25 12:55 UTC, carperimb commented on pages/deposit.page.js
> +    async accountSelector(){
I don't want to select the first item so I added the index, I think the name I gave it is correct...

2022-01-25 13:02 UTC, carperimb commented on tests/deposit.test.js
> +        expect (await depositPage.getPageTitle()).toHaveText('Deposit');
done

2022-01-25 13:10 UTC, carperimb commented on tests/deposit.test.js
> +            expect(obtainedAccount.getLastTransaction()).toHaveText('$50.00');
done

2022-01-25 13:11 UTC, carperimb commented on tests/deposit.test.js
> +            expect (await DepositPage.getDepositAmount()).toHaveText('');
done

2022-01-25 13:19 UTC, carperimb commented on pages/deposit.page.js
> +    async completeDepositForm(deposit){
completeDepositForm(deposit) is the best way I found to implement DDT...

2022-01-25 17:03 UTC, rquintana-abstracta commented on pages/deposit.page.js
> +    async accountSelector(){
In this case, consider `selectAccountByIndex()`. The problem with your current name is that is using the usual convention for object / class names, not functions, as it's esentially a substantive or a name for an object (the `accountSelector` object). For method names, the standard is starting it with a verb, indicating an action (as OOP calling semantics tipically goes like: `ObjectA.doesSomething()`).

2022-01-25 17:11 UTC, rquintana-abstracta commented on pages/deposit.page.js
> +    async completeDepositForm(deposit){
You can implement it in the same way you are doing it at the moment, only difference is that you will directly pass the relevant parameters to the `completeDepositForm()` method, instead of solving that inside the method body.

Like this (from `tests/deposit.test.js`):

```javascript
await DepositPage.completeDepositForm(deposit.acountSelectorIndex, deposit.depositAmount);
```

2022-01-25 17:14 UTC, rquintana-abstracta commented on tests/deposit.test.js
> +//import { expect } from "chai";
I still see it

2022-01-25 17:18 UTC, rquintana-abstracta commented on pages/checking.page.js
> +  }
This is obsolete with new implementation.

2022-01-25 17:19 UTC, rquintana-abstracta commented on pages/deposit.page.js
> +    }
These are obsolete as well

2022-01-25 17:20 UTC, rquintana-abstracta commented on pages/deposit.page.js
> +    } */
IMO, this should be the signature for `completeDepositForm()`. Consider uncommenting it and using it instead of your current one.

2022-01-25 17:53 UTC, rquintana-abstracta requested changes
Implement requested changes

2022-01-25 18:42 UTC, carperimb commented on tests/deposit.test.js
> +//import { expect } from "chai";
done

2022-01-25 18:44 UTC, carperimb commented on tests/deposit.test.js
> +            //expect (await DepositPage.getDepositAmount()).toHaveText('');
ok

2022-01-25 18:45 UTC, carperimb commented on pages/checking.page.js
> +  }
ok

2022-01-25 18:45 UTC, carperimb commented on pages/deposit.page.js
> +    }
ok

2022-01-25 18:55 UTC, carperimb commented on pages/deposit.page.js
> +    async completeDepositForm(deposit){
I cannot use it as you mentioned... it gave me a lot of errors...

2022-01-25 18:55 UTC, carperimb commented on pages/deposit.page.js
> +    } */
Nothing happens when I run this code instead of the current code, only fustration...

2022-01-26 15:46 UTC, carperimb commented on pages/deposit.page.js
> +    async completeDepositForm(deposit){
done

2022-01-26 17:02 UTC, rquintana-abstracta requested changes
Implement changes

2022-01-27 16:11 UTC, merged