Withdrawals
santiago-abstracta/digital-bank-bugbusters pull request #4
Opened 2022-01-08 15:53 UTC by santiago-abstracta

Hi! I'm creating this pull request in order to merge the withdrawls branch into main. This is a list of all the changes it makes:

- Changes `PAGE_TIMEOUT` value.
- Updates login, logout and signup test-cases in order to adapt assertions to use the `await expect(element).method()` implementation to avoid false positives.
- Updates test_cases.md to add new test-cases.
- Adds corresponding _Page Object_ to store needed web elements and methods.
- Adds tests following _Data Driven Testing_ method.

2022-01-11 14:32 UTC, rquintana-abstracta commented on pages/login.page.js
> +    return $('[class="badge badge-pill badge-danger"]');
Here you can use a simple, single class css selector and avoid coupling this one with purely style related classes such as badge-pill. eg. `.badge-danger`

2022-01-11 14:34 UTC, rquintana-abstracta commented on pages/login.page.js
> +    return $('[class="badge badge-pill badge-success"]');
Same comment here with `.badge-success`

2022-01-11 14:37 UTC, rquintana-abstracta commented on pages/signup.page.js
> +    return $('[class="badge badge-pill badge-danger"]');
same here

2022-01-11 14:37 UTC, rquintana-abstracta commented on pages/signup.page.js
> +    return $('[class="badge badge-pill badge-success"]');
same here

2022-01-11 14:39 UTC, santiago-abstracta commented on pages/login.page.js
> +    return $('[class="badge badge-pill badge-danger"]');
Yes! That's what I tried to do, but it won't work unless I include all the classes. Since expect assertions weren't working, that wasn't a problem before. Now that they do work, I noticed that every element I try to obtain using one (or some and not all) classes aren't found.

2022-01-11 14:47 UTC, rquintana-abstracta commented on pages/login.page.js
> +    return $('[class="badge badge-pill badge-danger"]');
Are you using standard "dot based" class selection for css when trying that? Because I understand that when  full element[attribute=value] syntax is used it requires the whole class chain, but was not aware of that happening when using `.class-name` syntax

2022-01-11 14:53 UTC, santiago-abstracta commented on pages/login.page.js
> +    return $('[class="badge badge-pill badge-danger"]');
Yep, that's the problem :0

2022-01-11 16:11 UTC, rquintana-abstracta commented on pages/withdraw.page.js
> +  get transactionsDiv() {
Div is too low level and bounded to a specific implementation detail. What is this element representing in user's terms? I assume it is a table, therefore prefer using that.

2022-01-11 16:14 UTC, rquintana-abstracta commented on pages/withdraw.page.js
> +  async selectAccountForWithdraw(account) {
It seems unnecessary to bound this method to the structure of an account object when you are only using one attribute from there. Make the data source / structure as transparent as possible for the method using it whenever possible in order to avoid unnecessary information coupling. For this case, prefer passing an account number / id directly instead of the whole account.

2022-01-11 16:17 UTC, rquintana-abstracta commented on pages/withdraw.page.js
> +    await this.accountForWithdrawMenu.selectByAttribute(
Wdio provides a more specific method for selecting by value on a select-like object (`selectByValue()`) that only needs one parameter for the value to be passed. Prefer using that to avoid the extra "value" parameter.

Ref: http://v4.webdriver.io/api/action/selectByValue.html

2022-01-11 16:21 UTC, rquintana-abstracta commented on tests/withdraw.test.js
> +    it("should withdraw specified amount from selected account when submit button is pressed", async () => {
I think you can parameterize this test name using the specific account name you are withdrawing from, that you currently have on your accountsForWithdraw array 

eg.

```javascript

it(`should withdraw specified amount from ${account.name} when submit button is pressed`, async () => {
```

2022-01-11 16:55 UTC, rquintana-abstracta commented on tests/withdraw.test.js
> +      );
Make sure to place this logic on a **beforeEach hook** for resusing it throughout the suite

2022-01-11 16:56 UTC, rquintana-abstracta commented on pages/withdraw.page.js
> +class Withdraw extends BasePage {
Standard you've been using for page object names was adding a Page suffix after class name. Add it here as well.

2022-01-11 21:51 UTC, rquintana-abstracta commented on tests/withdraw.test.js
> +    it("should show the account balance of the previously selected account", async () => {
Same comment regarding adding a parameterized account name as test description.

2022-01-11 21:51 UTC, rquintana-abstracta commented on tests/withdraw.test.js
> +    it("shouldn't let the user withdraw from selected account if specified amount is more than balance when submit button is pressed", async () => {
Same comment about parameterizing account name in test description

2022-01-11 21:55 UTC, rquintana-abstracta requested changes
Implement requested changes

2022-01-11 21:59 UTC, rquintana-abstracta commented on pages/withdraw.page.js
> +    return $("div=Transactions");
Also, if this is the transactions table, then this belongs to the checkings or savings account's pages, not to the Withdraw page

2022-01-12 16:11 UTC, santiago-abstracta commented on pages/login.page.js
> +    return $('[class="badge badge-pill badge-success"]');
Done!

2022-01-12 16:12 UTC, santiago-abstracta commented on pages/signup.page.js
> +    return $('[class="badge badge-pill badge-danger"]');
Done!

2022-01-12 16:13 UTC, santiago-abstracta commented on pages/signup.page.js
> +    return $('[class="badge badge-pill badge-success"]');
Done!

2022-01-12 16:19 UTC, santiago-abstracta commented on pages/withdraw.page.js
> +  get transactionsDiv() {
Done!

2022-01-12 16:23 UTC, santiago-abstracta commented on pages/withdraw.page.js
> +  async selectAccountForWithdraw(account) {
Done!

2022-01-13 01:03 UTC, santiago-abstracta commented on pages/withdraw.page.js
> +    await this.accountForWithdrawMenu.selectByAttribute(
The reason I didn't use the `selectByValue()` method is because it belongs to WebDriverIO v4, and it seems that it no longer works. 
According to the documentation, this is how it should be implemented: `browser.selectByValue(selector,value)`, which I tried and didn't work. I also tried something like this: `await this.accountForWithdrawMenu.selectByValue(accountNumber)`, but it didn't work either.

2022-01-13 13:13 UTC, santiago-abstracta commented on tests/withdraw.test.js
> +    it("should withdraw specified amount from selected account when submit button is pressed", async () => {
Done!

2022-01-13 14:23 UTC, santiago-abstracta commented on tests/withdraw.test.js
> +      );
It seems that the `beforeEach` hook only runs once per test, so I found out that this is what I can do instead of placing it right before the first test:
```
accountsForWithdraw.forEach((account) => {
    beforeEach(async function () {
      await LoginPage.open("login");
      await LoginPage.logInWithoutRememberMe(
        validAccount.username,
        validAccount.password
      );
    });
```
This means that the `beforeEach` hook should be included in every test that uses the `forEach` method, and, even though it might work, I can't tell the difference between this and what's already implemented. What shall I do?

2022-01-13 14:30 UTC, santiago-abstracta commented on pages/withdraw.page.js
> +class Withdraw extends BasePage {
Done!

2022-01-13 15:08 UTC, santiago-abstracta commented on tests/withdraw.test.js
> +    it("should show the account balance of the previously selected account", async () => {
Done!

2022-01-13 15:09 UTC, santiago-abstracta commented on tests/withdraw.test.js
> +    it("shouldn't let the user withdraw from selected account if specified amount is more than balance when submit button is pressed", async () => {
Done!

2022-01-13 19:22 UTC, santiago-abstracta commented on pages/withdraw.page.js
> +    return $("div=Transactions");
Done!

2022-01-13 22:42 UTC, rquintana-abstracta commented on pages/withdraw.page.js
> +    await this.accountForWithdrawMenu.selectByAttribute(
Ok, odd API design decision from the wdio team, but good to know that we aimed for using the cleaner API first.

2022-01-13 22:47 UTC, rquintana-abstracta commented on tests/withdraw.test.js
> +    it.only(`should withdraw specified amount from ${account.name} when submit button is pressed`, async () => {
Remove this `only()` call, as it's probably for debugging purposes

2022-01-13 22:49 UTC, rquintana-abstracta commented on tests/withdraw.test.js
> +    );
You forgot to delete this, as it's in the beforeEach hook

2022-01-13 22:52 UTC, santiago-abstracta commented on tests/withdraw.test.js
> +    it.only(`should withdraw specified amount from ${account.name} when submit button is pressed`, async () => {
Done!

2022-01-13 22:53 UTC, santiago-abstracta commented on tests/withdraw.test.js
> +    );
Done!

2022-01-13 22:53 UTC, rquintana-abstracta commented on tests/withdraw.test.js
> +      );
For the records, the problem with this was that, if test description is not parameterized, all the tests declared on the forEach get resolved as only one test, therefore the hook runs only once. It seems to rely on test name / description to determine tests equality.

2022-01-13 23:00 UTC, rquintana-abstracta approved these changes

2022-01-13 23:01 UTC, merged