Account API REST
santiago-abstracta/digital-bank-bugbusters pull request #7
Opened 2022-02-04 17:26 UTC by carperimb

New tests added.

2022-02-04 17:41 UTC, rquintana-abstracta commented on data/accounts.js
> -module.exports = {
This file mixes data from at least 2 different entities: User Accounts and Bank Accounts, so it makes sense to separate them, as it's getting really long.

2022-02-04 17:43 UTC, rquintana-abstracta commented on dictionaries/status_code.js
> +export const httpStatusCode = {
This folder name is a little bit too generic. Consider just defining the file in the root directory, as it doesn't seem necessary to create a one file directory. Also, rename it to `status_codes.js` (plural)

2022-02-04 17:44 UTC, rquintana-abstracta commented on tests/account.spec.js
> +    //console.log(response.data);
Remove commented code

2022-02-04 17:44 UTC, rquintana-abstracta commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.ok);
Consider if it can also be asserted that the accounts returned are effectively of type "checking" (a validation based on the returned data as well, not only status code)

2022-02-04 17:45 UTC, rquintana-abstracta commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.ok);
Same comment about validating the received data alongside the status code

2022-02-04 17:46 UTC, rquintana-abstracta commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.ok);
Same comment about validating data as well

2022-02-04 17:46 UTC, rquintana-abstracta commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.ok);
Same comment about validating data

2022-02-04 17:46 UTC, rquintana-abstracta commented on tests/account.spec.js
> +  /* accountsForWithdraw.forEach((account) => {
Remove commented code

2022-02-04 17:48 UTC, rquintana-abstracta commented on tests/account.spec.js
> +  before(async function () {
Convention is placing **before** hooks at the beginning of the suite. Consider moving it there.

2022-02-04 17:48 UTC, rquintana-abstracta commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.ok);
Same comment about validating data (assert that the returned account effectively has the passed id, for example)

2022-02-04 17:49 UTC, rquintana-abstracta commented on tests/account.spec.js
> +  it.skip(`should update created account`, async() => {
This is skipped, I assume it is related to the comment it has about failing the assertion. Review this

2022-02-04 17:50 UTC, rquintana-abstracta commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.ok);//expected: 200 actual: 400!
Also, consider retrieving the resource after updating it to check that it has fields with the changes you made (validation based on data)

2022-02-04 17:51 UTC, rquintana-abstracta commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.ok);
Same comment regarding asserting something on the response data for validating this (like making sure it has the owner id you expect)

2022-02-04 17:52 UTC, rquintana-abstracta commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.noContent);
Similar as in the rest of the cases, consider making sure you get a 404 when attempting to retrieve that account after deleting it to make sure the processed was correctly functionally executed (apart from the status code)

2022-02-04 17:53 UTC, rquintana-abstracta requested changes
Implement requested changes

2022-02-07 14:03 UTC, carperimb commented on data/accounts.js
> -module.exports = {
Done

2022-02-07 14:05 UTC, carperimb commented on dictionaries/status_code.js
> +export const httpStatusCode = {
Done

2022-02-07 15:11 UTC, carperimb commented on tests/account.spec.js
> +  /* accountsForWithdraw.forEach((account) => {
Done

2022-02-07 15:11 UTC, carperimb commented on tests/account.spec.js
> +  before(async function () {
Done

2022-02-07 15:12 UTC, carperimb commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.ok);
Done

2022-02-07 15:12 UTC, carperimb commented on tests/account.spec.js
> +  it.skip(`should update created account`, async() => {
Done

2022-02-07 15:12 UTC, carperimb commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.ok);//expected: 200 actual: 400!
Done

2022-02-07 15:14 UTC, carperimb commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.noContent);
AssertionError: expected undefined to equal 404

2022-02-07 15:31 UTC, carperimb commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.noContent);
Done

2022-02-07 22:56 UTC, carperimb commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.ok);
Done

2022-02-07 22:59 UTC, carperimb commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.ok);
Done

2022-02-07 23:00 UTC, carperimb commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.ok);
Done

2022-02-07 23:00 UTC, carperimb commented on tests/account.spec.js
> +    expect(response.status).to.equal(httpStatusCode.ok);
Done

2022-02-08 20:40 UTC, rquintana-abstracta commented on tests/account.spec.js
> +    let response = await axios.put(`/account/${createdAccountId}?newName=Updated`);
Axios provides support for building the URL based on its constitutive parts. For URL query parameters (the ones that go after a `?` in the URL), you can pass a third parameter to axios' `.put()` and under the key "params", you can place all the query string parameters as a key-value pair. This decouples the information from its representation in the final URL and takes care of potential formatting isues:

```javascript
let response = await axios.put(`/account/${createdAccountId}, {}, {params: {newName: "Updated"}});
```

Notice the empty object `{}` as the second parameter. This is needed as this endpoint doesn't take any body data (as is typical of POST, PUT and PATCH requests), and axios expects the second parameter to be the request body.

2022-02-08 20:42 UTC, rquintana-abstracta requested changes
Implement requested changes

2022-02-09 12:51 UTC, carperimb commented on tests/account.spec.js
> +    let response = await axios.put(`/account/${createdAccountId}?newName=Updated`);
This way it returns a 400...

2022-02-09 13:09 UTC, carperimb commented on tests/account.spec.js
> +    let response = await axios.put(`/account/${createdAccountId}?newName=Updated`);
Done...

2022-02-09 16:32 UTC, rquintana-abstracta approved these changes

2022-02-09 16:34 UTC, merged